Hotfix/unit test fdescribe
dvsa/mes-mobile-app pull request #1035
Opened 2019-12-13 17:05 UTC by ammarhaiderbjss

## Description
- Uses lodash's `cloneDeep` when working with `initialState` in the vehicle checks reducer tests.
- The nested array structure of the state object and using the spread operator (`...initialState`) to copy state was causing cross contamination issues when running tests.

## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/33695049/70818057-d0172b00-1dca-11ea-9456-c5a1a6ba805d.png)

2019-12-13 17:44 UTC, TomBillingtonUK approved these changes
Nice find :)

2019-12-16 08:37 UTC, MarkPatt89 approved these changes
Awesome work

2019-12-16 09:14 UTC, szabikr commented on src/pages/test-report/cat-be/components/vehicle-checks/vehicle-checks.scss
> +vehicle-checks {
Should we name this component `vehicle-checks-office`? The selector is called that, but maybe we could name the files that way as well

2019-12-16 10:09 UTC, edwardwilson requested changes
I would like to investigate the reducer further before we merge as I think there might be a run time bug here

2019-12-16 10:50 UTC, edwardwilson approved these changes
I have checked and the behaviour seen in the unit tests does not appear at runtime!

2019-12-16 12:45 UTC, merged