MES-4529 / Update debrief page for sub category c
dvsa/mes-mobile-app pull request #1159
Opened 2020-01-23 14:45 UTC by matthew2564

## Description
Add debrief show me tell me questions for the sub category c tests
## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

2020-01-23 15:01 UTC, amobarak commented on src/assets/i18n/cy.json
> +        "S17": "[Cy] Rear fog lights",
Nice spot

2020-01-23 15:22 UTC, appleabs approved these changes

2020-01-23 16:00 UTC, mgoldson requested changes
Looks good, will approve once the lint issue is fixed.

2020-01-23 16:00 UTC, mgoldson commented on src/providers/fault-summary/fault-summary.ts
> +import { CatBUniqueTypes } from "@dvsa/mes-test-schema/categories/B";
This should throw a lint error due to the double quotes

2020-01-24 09:47 UTC, mgoldson approved these changes

2020-01-24 10:19 UTC, merged