Mes 4725 speed check card data
dvsa/mes-mobile-app pull request #1225
Opened 2020-02-05 09:16 UTC by andrewsetterfield

## Description

Mod1 - link speed check data captured on test report to speed check card on debrief page.
https://jira.dvsacloud.uk/browse/MES-4725

## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

![Screenshot 2020-02-05 at 09 16 16](https://user-images.githubusercontent.com/48550267/73827854-31221480-47f8-11ea-89ca-c71a8f80c127.png)

2020-02-05 09:50 UTC, szabikr approved these changes

2020-02-05 10:26 UTC, mgoldson approved these changes

2020-02-05 10:39 UTC, edwardwilson requested changes
Looks like there needs to be some changes to the card to hide the avoidance when it wasn't attempted

2020-02-06 10:12 UTC, edwardwilson approved these changes

2020-02-06 10:12 UTC, merged