MES-4921-PCV-Doorexercise - analytics for PCV
dvsa/mes-mobile-app pull request #1319
Opened 2020-02-20 12:29 UTC by a0dexx

## Description

## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

2020-02-20 13:08 UTC, appleabs reviewed
Looks good :) You just need to write the tests

2020-02-20 14:05 UTC, TomBillingtonUK requested changes
Needs Unit Tests

2020-02-24 14:18 UTC, Cavalier07 commented on src/providers/analytics/analytics.model.ts
> +
I think it would be better to use the generic constants rather then creating new ones.  Like ADD_DRIVING_FAULT or ADD_SERIOUS_FAULT

2020-02-24 14:18 UTC, TomBillingtonUK approved these changes

2020-02-24 14:20 UTC, appleabs approved these changes

2020-02-24 14:39 UTC, merged