Mes 4776 cat1 e full journey
dvsa/mes-mobile-app pull request #1351
Opened 2020-02-27 14:55 UTC by turnerc1

## Description

## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

2020-02-27 14:58 UTC, szabikr approved these changes

2020-02-28 09:22 UTC, jono-basford-bjss requested changes

2020-02-28 09:22 UTC, jono-basford-bjss commented on test/e2e/step-definitions/testreport-steps.ts
> +  const diagramModalTitle = getElement(by.xpath('//reverse-diagram-modal//div[2]'));
have you tested this on the cat c full user journey feature?

2020-02-28 09:22 UTC, jono-basford-bjss commented on test/e2e/step-definitions/testreport-steps.ts
> +    const manoeuvresButton = getElement(by.xpath('//competency-button[contains(@class, "reverse-left-tick")]'));
can you create a common function which does this please

2020-02-28 09:22 UTC, jono-basford-bjss commented on test/e2e/step-definitions/testreport-steps.ts
>      const manoeuvresButton = getElement(by.xpath('//competency-button[contains(@class, "reverse-left-tick")]'));
single function please

2020-02-28 09:22 UTC, jono-basford-bjss commented on test/e2e/step-definitions/waitingroom-steps.ts
> +
remove white space

2020-02-28 09:22 UTC, jono-basford-bjss commented on test/e2e/step-definitions/waitingroomtocar-steps.ts
> -});
Removing this will cause the other tests to fail

2020-02-28 09:22 UTC, jono-basford-bjss commented on test/e2e/step-definitions/waitingroomtocar-steps.ts
> +
remove white space

2020-02-28 09:47 UTC, turnerc1 commented on test/e2e/step-definitions/testreport-steps.ts
> +  const diagramModalTitle = getElement(by.xpath('//reverse-diagram-modal//div[2]'));
I have tested it with cat c full journey and it all works fine

2020-02-28 09:50 UTC, jono-basford-bjss commented on test/e2e/step-definitions/testreport-steps.ts
> +  const diagramModalTitle = getElement(by.xpath('//reverse-diagram-modal//div[2]'));
👍

2020-02-28 09:51 UTC, turnerc1 commented on test/e2e/step-definitions/waitingroom-steps.ts
> +
Done.

2020-02-28 09:57 UTC, turnerc1 commented on test/e2e/step-definitions/waitingroomtocar-steps.ts
> -});
> Removing this will cause the other tests to fail

I have removed this because it is a duplicate

2020-02-28 09:58 UTC, turnerc1 commented on test/e2e/step-definitions/waitingroomtocar-steps.ts
> +
Done

2020-02-28 10:23 UTC, turnerc1 commented on test/e2e/step-definitions/testreport-steps.ts
> +    const manoeuvresButton = getElement(by.xpath('//competency-button[contains(@class, "reverse-left-tick")]'));
Done.

2020-02-28 10:23 UTC, turnerc1 commented on test/e2e/step-definitions/testreport-steps.ts
>      const manoeuvresButton = getElement(by.xpath('//competency-button[contains(@class, "reverse-left-tick")]'));
Done.

2020-02-28 10:30 UTC, jono-basford-bjss commented on test/e2e/step-definitions/waitingroomtocar-steps.ts
> -});
👍

2020-02-28 12:19 UTC, jono-basford-bjss requested changes

2020-02-28 12:19 UTC, jono-basford-bjss commented on test/e2e/step-definitions/journal-steps.ts
> +When('I rekey a test for {string}', (candidateName, unitname) => {
whats 'unitname'?

2020-02-28 12:19 UTC, jono-basford-bjss commented on test/e2e/step-definitions/waitingroom-steps.ts
> +
white space

2020-02-28 12:19 UTC, jono-basford-bjss commented on test/e2e/step-definitions/waitingroom-steps.ts
> +
white space

2020-02-28 13:01 UTC, turnerc1 commented on test/e2e/step-definitions/waitingroom-steps.ts
> +
Done

2020-02-28 13:01 UTC, turnerc1 commented on test/e2e/step-definitions/waitingroom-steps.ts
> +
Done

2020-02-28 13:01 UTC, turnerc1 commented on test/e2e/step-definitions/journal-steps.ts
> +When('I rekey a test for {string}', (candidateName, unitname) => {
Removed

2020-02-28 13:30 UTC, jono-basford-bjss approved these changes
looks good

2020-02-28 13:39 UTC, merged