Mes ms 4783 catc1e fail journey
dvsa/mes-mobile-app pull request #1399
Opened 2020-03-05 15:08 UTC by turnerc1

## Description
Cat c1e failed journey
## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

2020-03-05 15:28 UTC, turnerc1 commented
This is @JCarterDVSA story

2020-03-06 10:57 UTC, jono-basford-bjss requested changes

2020-03-06 10:57 UTC, jono-basford-bjss commented on test/e2e/step-definitions/waitingroomtocar-steps.ts
> +  console.log('table', table);
dont need this, please remove

2020-03-06 10:57 UTC, jono-basford-bjss commented on test/e2e/step-definitions/waitingroom-steps.ts
> +Before({ tags: '@catc1e' }, () => {
we already have a c1e

2020-03-06 10:57 UTC, jono-basford-bjss commented on test/e2e/step-definitions/waitingroomtocar-steps.ts
> +    console.log('------------------------------------------------------------');
remove

2020-03-06 10:57 UTC, jono-basford-bjss commented on test/e2e/step-definitions/waitingroomtocar-steps.ts
> +    console.log('UI TEST DATA ce: ', UI_TEST_DATA.testData.ce);
please remove

2020-03-06 10:58 UTC, closed without merging