Mes 4919 home test wrtc
dvsa/mes-mobile-app pull request #1443
Opened 2020-03-11 15:57 UTC by a0dexx

## Description

## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

2020-03-11 16:24 UTC, appleabs commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/__tests__/vehicle-checks.cat-home-test.selector.spec.ts
> +import { CatBEUniqueTypes } from '@dvsa/mes-test-schema/categories/BE';
wrong category

2020-03-11 16:24 UTC, appleabs commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/__tests__/vehicle-checks.cat-home-test.selector.spec.ts
> +      const emptyVehicleChecks: CatBEUniqueTypes.VehicleChecks = { showMeQuestions: [{}], tellMeQuestions: [{}] };
category needs updating

2020-03-11 16:24 UTC, appleabs commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/__tests__/vehicle-checks.cat-home-test.selector.spec.ts
> +      const populatedVehicleChecks: CatBEUniqueTypes.VehicleChecks =
category needs updating

2020-03-11 16:24 UTC, appleabs commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/__tests__/vehicle-checks.cat-home-test.selector.spec.ts
> +      const populatedVehicleChecks: CatBEUniqueTypes.VehicleChecks =
category needs updating

2020-03-11 16:25 UTC, appleabs commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/vehicle-checks.cat-home-test.reducer.ts
> +  from '../../../../../shared/constants/show-me-questions/show-me-questions.cat-be.constants';
category needs updating

2020-03-11 16:25 UTC, appleabs commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/vehicle-checks.cat-home-test.reducer.ts
> +  from '../../../../../shared/constants/tell-me-questions/tell-me-questions.cat-be.constants';
category needs updating

2020-03-11 16:26 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/__tests__/waiting-room-to-car.cat-home-test.page.spec.ts
> +import { PracticeModeBanner } from '../../../../components/common/practice-mode-banner/practice-mode-banner';
remove practice mode banner

2020-03-11 16:27 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/__tests__/waiting-room-to-car.cat-home-test.page.spec.ts
> +        MockComponent(PracticeModeBanner),
remove practice banner

2020-03-11 16:28 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/__tests__/waiting-room-to-car.cat-home-test.page.spec.ts
> +      // tslint:disable-next-line:max-line-length
why is lint disabled?

2020-03-11 16:28 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/__tests__/waiting-room-to-car.cat-home-test.page.spec.ts
> +      // tslint:disable-next-line:max-line-length
same as above

2020-03-11 16:29 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/__tests__/vehicle-checks-modal.cat-home-test.analytics.effects.spec.ts
> +  from '../../../../../../modules/tests/test-data/cat-be/vehicle-checks/vehicle-checks.cat-be.action';
category needs updating

2020-03-11 16:31 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/__tests__/vehicle-checks-modal.cat-home-test.page.spec.ts
> +  describe('DOM', () => {
This is empty could be deleted?

2020-03-11 16:32 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.analytics.effects.ts
> +} from '../../../../../modules/tests/test-data/cat-be/vehicle-checks/vehicle-checks.cat-be.action';
category needs implementing

2020-03-11 16:33 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.module.ts
> +export class VehicleChecksModalCatBEModule { }
correct category needs implementing

2020-03-11 16:33 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.scss
> +vehicle-checks-modal-cat-be {
correct category needs implementing

2020-03-11 16:33 UTC, Cavalier07 commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks/__tests__/vehicle-checks.spec.ts
> +describe('VehicleChecksCatBEComponent', () => {
Bad describe

2020-03-11 16:33 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.ts
> +import { getTestData } from '../../../../../modules/tests/test-data/cat-be/test-data.cat-be.reducer';
correct category needs implementing

2020-03-11 16:34 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.ts
> +import { getCandidate } from '../../../../../modules/tests/journal-data/cat-be/candidate/candidate.cat-be.reducer';
correct category needs implementing

2020-03-11 16:34 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.ts
> +} from '../../../../../modules/tests/test-data/cat-be/vehicle-checks/vehicle-checks.cat-be.action';
correct category needs implementing

2020-03-11 16:34 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.ts
> +} from '../../../../../shared/constants/tell-me-questions/tell-me-questions.cat-be.constants';
correct category needs implementing

2020-03-11 16:35 UTC, Cavalier07 commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks/vehicle-checks.scss
> +vehicle-checks-cat-be {
you need to update this

2020-03-11 16:35 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.ts
> +} from '../../../../../shared/constants/show-me-questions/show-me-questions.cat-be.constants';
correct category needs implementing

2020-03-11 16:36 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.ts
> +    this.showMeQuestions = questionProvider.getShowMeQuestions(TestCategory.BE);
correct category needs implementing

2020-03-11 16:37 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.ts
> +          return this.faultCountProvider.getVehicleChecksFaultCount(TestCategory.BE, vehicleChecks);
correct category needs implementing

2020-03-11 16:52 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks/__tests__/vehicle-checks.spec.ts
> +    describe('DOM', () => {
remove empty describe

2020-03-11 16:53 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/waiting-room-to-car.cat-home-test.page.html
> +      <end-test-link category="B+E"></end-test-link>
incorrect category

2020-03-11 16:54 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/waiting-room-to-car.cat-home-test.page.ts
> +import { getVehicleDetails } from '../../../modules/tests/vehicle-details/cat-be/vehicle-details.cat-be.reducer';
category needs implementing

2020-03-11 16:54 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/waiting-room-to-car.cat-home-test.page.ts
> +} from '../../../modules/tests/vehicle-details/cat-be/vehicle-details.cat-be.selector';
category needs implementing

2020-03-11 16:54 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/waiting-room-to-car.cat-home-test.page.ts
> +import { getCandidate } from '../../../modules/tests/journal-data/cat-be/candidate/candidate.cat-be.reducer';
category needs implementing

2020-03-11 16:54 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/waiting-room-to-car.cat-home-test.page.ts
> +import { CatBEUniqueTypes } from '@dvsa/mes-test-schema/categories/BE';
category needs implementing

2020-03-11 16:54 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/waiting-room-to-car.cat-home-test.page.ts
> +    this.tellMeQuestions = questionProvider.getTellMeQuestions(TestCategory.BE);
category needs implementing

2020-03-11 16:55 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/waiting-room-to-car.cat-home-test.page.ts
> +          return this.faultCountProvider.getVehicleChecksFaultCount(TestCategory.BE, vehicleChecks);
category needs implementing

2020-03-11 16:55 UTC, appleabs reviewed
A few categories need to be implemented, or to-dos added happy to approve when this is done :)

2020-03-11 17:11 UTC, mgoldson reviewed
Looks like a few category refs to BE still left to catch but looking good!

2020-03-11 17:11 UTC, mgoldson commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/__tests__/vehicle-checks-modal.cat-home-test.analytics.effects.spec.ts
> +    it('should log an analyics event with tell me question info', (done) => {
I'm sure it is incorect in the category copied from but let's break the chain now. Typo in 'analytics'.

2020-03-11 17:11 UTC, mgoldson commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/__tests__/vehicle-checks-modal.cat-home-test.page.spec.ts
> +} from '../../../../../../modules/tests/test-data/cat-be/vehicle-checks/vehicle-checks.cat-be.action';
Use cat-home action if it is available.

2020-03-12 10:52 UTC, a0dexx commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/vehicle-checks.cat-home-test.reducer.ts
> +  from '../../../../../shared/constants/tell-me-questions/tell-me-questions.cat-be.constants';
todo added

2020-03-12 10:52 UTC, a0dexx commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/vehicle-checks.cat-home-test.reducer.ts
> +  from '../../../../../shared/constants/show-me-questions/show-me-questions.cat-be.constants';
todo added

2020-03-12 11:06 UTC, tomcrawleyy requested changes

2020-03-12 11:06 UTC, tomcrawleyy commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/vehicle-checks.cat-home-test.action.ts
> +
Missing InitializeVehicleChecks - this is mandatory for starting tests & will be needed to unblock the rest of the sprint, please don't forget this

2020-03-12 11:26 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/__tests__/waiting-room-to-car.cat-home-test.page.spec.ts
> +      // tslint:disable-next-line:max-line-length
was already like that

2020-03-12 11:26 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/__tests__/waiting-room-to-car.cat-home-test.page.spec.ts
> +      // tslint:disable-next-line:max-line-length
already like that

2020-03-12 11:28 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/__tests__/vehicle-checks-modal.cat-home-test.analytics.effects.spec.ts
> +  from '../../../../../../modules/tests/test-data/cat-be/vehicle-checks/vehicle-checks.cat-be.action';
done

2020-03-12 12:21 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/__tests__/vehicle-checks-modal.cat-home-test.page.spec.ts
> +} from '../../../../../../modules/tests/test-data/cat-be/vehicle-checks/vehicle-checks.cat-be.action';
adding todo for now

2020-03-12 12:23 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.analytics.effects.ts
> +} from '../../../../../modules/tests/test-data/cat-be/vehicle-checks/vehicle-checks.cat-be.action';
todo added

2020-03-12 12:32 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.module.ts
> +export class VehicleChecksModalCatBEModule { }
added todo

2020-03-12 14:27 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.ts
> +import { getCandidate } from '../../../../../modules/tests/journal-data/cat-be/candidate/candidate.cat-be.reducer';
todo added

2020-03-12 14:28 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.ts
> +import { getTestData } from '../../../../../modules/tests/test-data/cat-be/test-data.cat-be.reducer';
todo added

2020-03-12 14:38 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.ts
> +          return this.faultCountProvider.getVehicleChecksFaultCount(TestCategory.BE, vehicleChecks);
done

2020-03-12 14:45 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/waiting-room-to-car.cat-home-test.page.html
> +      <end-test-link category="B+E"></end-test-link>
todo added

2020-03-12 14:49 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/waiting-room-to-car.cat-home-test.page.ts
> +} from '../../../modules/tests/vehicle-details/cat-be/vehicle-details.cat-be.selector';
todo added

2020-03-12 14:50 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/waiting-room-to-car.cat-home-test.page.ts
> +    this.tellMeQuestions = questionProvider.getTellMeQuestions(TestCategory.BE);
todo added

2020-03-12 14:51 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/waiting-room-to-car.cat-home-test.page.ts
> +          return this.faultCountProvider.getVehicleChecksFaultCount(TestCategory.BE, vehicleChecks);
todo

2020-03-12 15:47 UTC, TomBillingtonUK approved these changes

2020-03-12 15:53 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-question/__tests__/vehicle-checks-question.spec.ts
> +  describe('DOM', () => {
remove empty describe

2020-03-12 16:02 UTC, tomcrawleyy submitted a review, later dismissed

2020-03-12 16:02 UTC, tomcrawleyy commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/vehicle-checks.cat-home-test.reducer.ts
> +    case vehicleChecksCatHomeTestActionTypes.SHOW_ME_QUESTION_SELECTED:
InitializeVehicleChecks should be here, this must be added in for the sprint to become unblocked.

2020-03-12 16:21 UTC, tomcrawleyy commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/vehicle-checks.cat-home-test.reducer.ts
> +    case vehicleChecksCatHomeTestActionTypes.SHOW_ME_QUESTION_SELECTED:
no longer applicable ^

2020-03-12 16:21 UTC, tomcrawleyy commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/vehicle-checks.cat-home-test.action.ts
> +
no longer applicable

2020-03-13 09:13 UTC, a0dexx commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.ts
> +    this.showMeQuestions = questionProvider.getShowMeQuestions(TestCategory.BE);
TestCategory.F added

2020-03-13 11:21 UTC, appleabs commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/vehicle-checks.cat-home-test.reducer.ts
> +  from '../../../../../shared/constants/tell-me-questions/tell-me-questions.cat-be.constants';
can you add a to-do on line 8 please

2020-03-13 11:21 UTC, appleabs commented on src/modules/tests/test-data/cat-home-test/vehicle-checks/vehicle-checks.cat-home-test.reducer.ts
> +  from '../../../../../shared/constants/show-me-questions/show-me-questions.cat-be.constants';
can you add a to-do on line 12 please

2020-03-13 11:24 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/waiting-room-to-car.cat-home-test.page.ts
> +  vehicleChecks$: Observable<CatBEUniqueTypes.VehicleChecks>;
can you add a to-do please

2020-03-13 11:27 UTC, appleabs commented on src/pages/waiting-room-to-car/cat-home-test/components/vehicle-checks-modal/vehicle-checks-modal.cat-home-test.page.module.ts
> +export class VehicleChecksModalCatBEModule { }
can you please put a to-do on line 23

2020-03-13 11:47 UTC, appleabs approved these changes

2020-03-13 11:56 UTC, merged