MES-5118 ADI2 Journey through to Autosave
dvsa/mes-mobile-app pull request #1521
Opened 2020-04-03 09:23 UTC by tomcrawleyy

## Description
Removes Health Declaration screen from ADI2 Journey
## Checklist

- [x] PR title includes the JIRA ticket number
- [x] Branch is rebased against the latest develop
- [x] Code has been tested manually
- [x] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

2020-04-03 12:55 UTC, andrewsetterfield approved these changes

2020-04-06 08:32 UTC, matthew2564 commented on src/pages/pass-finalisation/cat-adi-part2/pass-finalisation.cat-adi-part2.page.ts
> +      this.navController.push(CAT_ADI_PART2.BACK_TO_OFFICE_PAGE);
Should we be removing the views here like is done in the HEALTH_DECLARATION_PAGE?

2020-04-06 17:35 UTC, Cullima requested changes
Just a small change

2020-04-06 17:35 UTC, Cullima commented on src/pages/pass-finalisation/cat-adi-part2/_tests_/pass-finalisation.cat-adi-part2.page.spec.ts
> +  let navController$: NavController;
$ suffix convention signifies that the variable is an observable can you remove here

2020-04-07 06:18 UTC, andrewsetterfield approved these changes

2020-04-07 06:45 UTC, Cullima approved these changes

2020-04-07 06:50 UTC, merged