few changes and fixes
dvsa/mes-mobile-app pull request #1743
Opened 2020-08-25 13:13 UTC by naqvis5

## Description

## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

2020-08-25 13:22 UTC, andrewsetterfield approved these changes

2020-08-25 13:32 UTC, turnerc1 requested changes
I will review this later

2020-08-26 12:12 UTC, turnerc1 approved these changes

2020-09-18 10:58 UTC, closed without merging

2020-09-18 10:58 UTC, naqvis5 commented
sdsf