Mes 5959 cherry pick
dvsa/mes-mobile-app pull request #1817
Opened 2020-10-19 10:17 UTC by Cullima

## Description
- cherry pick of fixes to `release-3.8.0` #1812 #1813 #1814 #1815 #1816 
## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

2020-10-19 13:02 UTC, matthew2564 approved these changes

2020-10-20 07:07 UTC, andrewsetterfield requested changes

2020-10-20 07:07 UTC, andrewsetterfield commented on src/providers/authentication/authentication.ts
> +      logLevel: 'DEBUG',
are we leaving the loglevel set to debug?

2020-10-20 08:02 UTC, andrewsetterfield approved these changes

2020-10-21 06:27 UTC, merged