Mes 3632 bump test schema version
dvsa/mes-mobile-app pull request #785
Opened 2019-09-23 16:30 UTC by mgoldson

# Description and relevant Jira numbers
Use the latest version of the mes test schema, which includes a new version property:

**Schema change PR**
https://github.com/dvsa/mes-api-definitions/pull/75

**Corresponding Backend PR's**
https://github.com/dvsa/mes-result-service/pull/91
https://github.com/dvsa/mes-documents-service/pull/56
https://github.com/dvsa/mes-mi-export-service/pull/20
https://github.com/dvsa/mes-result-processing-service/pull/33

**Jira ticket**
https://jira.dvsacloud.uk/browse/MES-3632

## Pull Request checklist

- [x] [WIP] tag removed from PR title
- [x] PR has an understandable description

## Git feature branch checklist

- [x] branch name comply with our branching strategy
- [x] git branch contains relevant JIRA ticket number
- [x] branch rebased against the latest develop

## Sign off process checklist

- [ ] Code has been tested manually
- [ ] Tested by QA
- [ ] PO's approval
- [ ] Reviewers selected in Github
- [ ] PR link added to JIRA

2019-09-23 16:35 UTC, ammarhaiderbjss commented
@mgoldson Is the work to add schema version to the real test result to be done separately?

2019-09-23 16:37 UTC, ammarhaiderbjss requested changes
There seem to be a lot of version changes in `package-lock.json` can we ensure this is limited to the package that was updated please?

2019-09-23 17:06 UTC, ammarhaiderbjss approved these changes

2019-09-30 09:07 UTC, Cavalier07 commented
This PR is no longer needed

2019-09-30 09:07 UTC, closed without merging