Fix build
dvsa/mes-mobile-app pull request #795
Opened 2019-09-25 15:40 UTC by szabolcs-keresztes

## Description

This might be the fix for build.

2019-09-25 15:41 UTC, TomBillingtonUK approved these changes

2019-09-26 07:30 UTC, rossfauldsbjss commented on package-lock.json
>              "is-extglob": "^2.1.1"
Lots of version changes in the package lock - is this intended?

2019-09-26 07:34 UTC, rossfauldsbjss requested changes
Just want to make sure  all the package-lock changes are intentional for this fix.

2019-09-26 08:27 UTC, andrew-lai-bjss commented
There has been an update to the package and package-lock file in develop so don't expect this will merge in now.

2019-09-26 10:03 UTC, szabolcs-keresztes commented
This is not the most appropriate fix

2019-09-26 10:03 UTC, closed without merging