Feature/mes 3839 Display vehicle checks on debrief
dvsa/mes-mobile-app pull request #990
Opened 2019-12-04 10:35 UTC by edwardwilson

## Description

## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

2019-12-04 11:09 UTC, faggc approved these changes

2019-12-04 12:38 UTC, rossfauldsbjss commented on src/pages/debrief/cat-be/components/vehicle-checks-card/__tests__/vehicle-checks-card.spec.ts
> +// import { ComponentFixture, async, TestBed } from '@angular/core/testing';
Tests need to be uncommented and made to work.

2019-12-04 12:40 UTC, rossfauldsbjss requested changes
Tests commented out for Cat BE - they are just a copy of Cat B tests and should instead should be Cat BE specific tests

2019-12-04 17:08 UTC, ammarhaiderbjss commented
Missing a description as well as a screenshot for this :(

2019-12-12 10:46 UTC, rstepnowski commented
You should've rebased that branch against developing - so many changes already merged got pulled from develop on this one + there are still conflicts on this

2019-12-12 10:55 UTC, closed without merging